Revert "android: psi: __poll_t typedef for downstream"
Clang 15 returns this warning:

../drivers/android/psi.c:9:22: warning: redefinition of typedef '__poll_t' is a C11 feature [-Wtypedef-redefinition]
typedef unsigned int __poll_t;
                     ^
../include/uapi/linux/types.h:55:18: note: previous definition is here
typedef unsigned __poll_t;
                 ^
1 warning generated.

This reverts commit 4a9f8cbf52f0d0efbeee197a123abc7b01d36ac6.

Signed-off-by: Forest <forestd.github@gmail.com>