Revert "sched/clock: Move sched clock initialization and merge with"
reverted this since sched_clock has been updated recently in 4.14.285 d73f58abbf008145d02d3611d8b83e8bab318306

fixes:

../init/main.c:672:2: error: implicit declaration of function 'sched_clock_postinit' [-Werror,-Wimplicit-function-declaration]
        sched_clock_postinit();
        ^
../init/main.c:672:2: note: did you mean 'sched_clock_init'?
../include/linux/sched/clock.h:24:13: note: 'sched_clock_init' declared here
extern void sched_clock_init(void);
            ^
1 error generated.

This reverts commit 9e01bd7e5d60c9a153542e1b485e963bee7ba80f.

Signed-off-by: Forest <forestd.github@gmail.com>